"""add llm_primary to extractions

Revision ID: 4e3ff65651b7
Revises: d4e5f6a7b8c9
Create Date: 2026-07-23 20:44:50.890193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3ff65651b7'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extractions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_primary', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extractions', schema=None) as batch_op:
        batch_op.drop_column('llm_primary')

    # ### end Alembic commands ###
